### ISSUE TITLE
Failure to clone while lunching

### ISSUE THREAD

**Issue by PeterHindes** [theimpulson/android_device_asus_Z00T#1]
while lunching the error

`From https://github.com/theimpulson/android_device_asus_msm8916-common
  [new branch]      8.1.x      -> github/8.1.x
fatal: Couldn't find remote ref refs/heads/lineage-15.1 MiB/s   4), 4.21 MiB | 4.06 MiB/s
Unexpected end of command stream
error: Cannot fetch theimpulson/android_kernel_asus_msm8916/s`

is output while downloading and subsequently the error

`build/core/product_config.mk:242: *** _nic.PRODUCTS.[[device/asus/Z00T/aosp_Z00T.mk]]: "device/asus/msm8916-common/msm8916.mk" does not exist.  Stop.`

is caused, failing the build

**Comment by ghost** [comment]
Use from the organization, not my personal account.

**Comment by PeterHindes** [comment]
i dont quite understand

**Comment by ghost** [comment]
There is a manifest in the organization. Use that.
